title:        Philipp Boersch-Supan
tagline:      'Philipp Boersch-Supan'
description:  'Postdoctoral Researcher in Ecology'
url:    http://pboesu.github.io
version:      1.1.1
author:
  name:       Philipp Boersch-Supan
  email:      pboesu@gmail.com
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
gems:         [jekyll-paginate]
paginate:     5
paginate_path: "/blog/page:num/"
exclude: ["/imported/"]

